version: '3'

services:

  web:
    build: ./web
    container_name: web01
    ports: 
      - 80:8080
    environment:
      - "TZ=Japan"
    networks:
      - Yuri-Kabe_network
    volumes:
      - ./web/source:/var/www/
    
  store:
    build: ./store
    container_name: store01
    ports:
      - 6000:6000
    environment:
      - "TZ=Japan"
    networks: 
      - Yuri-Kabe_network
      
networks:
  Yuri-Kabe_network:
    driver: bridge